[package]
name = "notan_log"
version = "0.10.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2021"
readme = "README.md"
homepage = "https://github.com/Nazariglez/notan"
repository = "https://github.com/Nazariglez/notan"
license = "MIT OR Apache-2.0"
description = "Provides a multipatform log support for Notan"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan_app.workspace = true

log.workspace = true

fern = { version = "0.6.2", features = ["colored"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
time = { version = "0.3.21", features = ["formatting", "local-offset"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
js-sys.workspace = true

console_log = "1.0.0"
